# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'azarmpipel-conn'
    subscriptionId: '6db1b3d2-11b5-4c78-83f0-9490f7fe7770'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'azarmpipel-rg'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/Azure/azure-docs-json-samples/master/get-started-deployment/linked-template/azuredeploy.json'
    overrideParameters: '-projectName azarmpipel -storageSKU stamdard_GRS'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
  displayName: 'Run a multi-line script'
